name: Boot2Stack CI

on:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
    - master

env:
  WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
  WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}

jobs:
  controller:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: sudo /bin/bash create-controller-ovs-image.sh

      - name: push to wetransfer
        run: /bin/bash transfer.sh wet
  compute:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: sudo /bin/bash create-compute-ovs-image.sh

      - name: push to wetransfer
        run: /bin/bash transfer.sh wet
  storage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: sudo /bin/bash create-storage-image.sh

      - name: push to wetransfer
        run: /bin/bash transfer.sh wet
  gluster:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: sudo /bin/bash create-gluster-image.sh

      - name: push to wetransfer
        run: /bin/bash transfer.sh wet
  baremetal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: sudo /bin/bash create-baremetal-image.sh

      - name: push to wetransfer
        run: /bin/bash transfer.sh wet
